# Generated by Django 5.0.1 on 2024-02-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Slug',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
